### ISSUE TITLE
easymeme69.com Implementation

### ISSUE THREAD

**Issue by Tracer1337** [uvulpos/HelloCodingDE-DiscordBot-Issues#2]
Ich grüße mich :wave: (Tim grüße ich auch)

**Comment by Tracer1337** [comment]
Der Bot muss nur diesen Link senden: https://www.easymeme69.com/api/upload/random

**Comment by uvulpos** [comment]
Wenn ich den link einzeln reinschicke funktioniert es, aber ich kann ihn nicht einbetten. Ich bin mir nicht sicher aber evtl. bedient sich da Discord an den OG:Tags

**Comment by uvulpos** [comment]
super is programmiert. Danke für deinen Beitrag :)
