### ISSUE TITLE
Bot immediately removes rolle after adding it

### ISSUE THREAD

**Issue by ENDER-9** [uvulpos/HelloCodingDE-DiscordBot-Issues#6]
![IMG_20200812_215623.png](https://user-images.githubusercontent.com/54618409/90062195-998e0900-dce7-11ea-92ec-50e5738ac4ad.png)

**Comment by uvulpos** [comment]
![Screenshot](http://prntscr.com/tyn53n)

Ich hab eben den Bot mal neugestartet und dann war der Fehler weg. Ich lass das Ticket mal offen wenn nochmal was sein sollte einfach schreiben ansonsten kannst du das Ticket schließen

**Comment by ENDER-9** [comment]
Fehler ist wieder weg👍
